### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by kitaminary**
[DEMO LINK](https://kitaminary.github.io/layout_html-form/)
[TEST REPORT LINK](https://kitaminary.github.io/layout_html-form/report/html_report/)

### CODE REVIEW

**Comment by OleksandrHnelytskyi** [comment]
(https://OleksandrHnelytskyi.github.io/layout_html-form/)
(https://OleksandrHnelytskyi.github.io/layout_html-form/report/html_report/)

**Comment by Mikitkaaist** [comment]
https://Mikitkaaist.github.io/layout_html-form/
https://Mikitkaaist.github.io/layout_html-form/report/html_report/

**Comment by BoGoBooM** [comment]
[DEMO LINK](https://github.com/BoGoBooM/layout_html-form)
- [TEST REPORT LINK](https://BoGoBooM.github.io/layout_html-form/report/html_report/)

**Comment by Vladimir-Zadorozhnyi** [comment]
https://Vladimir-Zadorozhnyi.github.io/layout_html-form
https://Vladimir-Zadorozhnyi.github.io/layout_html-form/report/html_report/

**Comment by AndriyMachalaba** [comment]
https://AndriyMachalaba.github.io/layout_hello-world/ 
https://AndriyMachalaba.github.io/layout_hello-world/report/html_report/

**Pull request closed without merging**
